# Generated by Django 4.2 on 2023-05-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('dolares', models.BooleanField(verbose_name='Dolares')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('categoria', models.CharField(choices=[('Alquiler', 'Alquiler'), ('Venta', 'Venta')], max_length=10, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=100, verbose_name='Dirección Electrónica')),
                ('telefono', models.CharField(max_length=50, verbose_name='Número Telefónico')),
                ('habitaciones', models.IntegerField()),
                ('ambientes', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('niños', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Niños')),
                ('mascotas', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Mascotas')),
                ('garage', models.IntegerField(blank=True, null=True, verbose_name='Espacio del Garage')),
                ('duracion_contrato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Duración del Contrato')),
                ('expensas', models.IntegerField(blank=True, null=True, verbose_name='Expensas')),
                ('antiguedad', models.IntegerField(blank=True, null=True, verbose_name='Antigüedad de la Construcción')),
                ('destacado', models.BooleanField(verbose_name='Destacado')),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.propiedad')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
