# Generated by Django 4.2.1 on 2023-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_propiedad_numero_direccion_alter_propiedad_ambientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='inmobiliaria',
            field=models.CharField(default='Nombre de Inmobiliaria', max_length=50, verbose_name='Nombre de Inmobiliaria'),
        ),
    ]
