# Generated by Django 4.2.1 on 2023-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_propiedad_inmobiliaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='numero_inmobiliaria',
            field=models.CharField(default='2244-554488', max_length=50, verbose_name='Número de Inmobiliaria'),
        ),
    ]
