# Generated by Django 4.2.1 on 2023-05-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_propiedad_numero_inmobiliaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='numero_inmobiliaria',
            new_name='telefono_inmobiliaria',
        ),
    ]
