# Generated by Django 4.2.1 on 2023-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_propiedad_inmobiliaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='telefono_inmobiliaria',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Metros Cuadrados'),
        ),
    ]
