# Generated by Django 4.2.1 on 2023-06-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_propiedad_inmobiliaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='telefono_inmobiliaria',
        ),
    ]
