# Generated by Django 4.2.1 on 2023-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_remove_propiedad_inmobiliaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="info_extra",
            field=models.TextField(
                blank=True, null=True, verbose_name="Información extra"
            ),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="numero_direccion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de Dirección"
            ),
        ),
    ]
